- scr/Plugin.LocalNotification/Platform/iOS/LocalNotificationService.cs
Previously, if NotifyTime property is not set before calling Show method, the notification will only work correctly for the first time. Now the notification will pop up every time when notification is receive.
> Fixed notification in iOS not poping up if NotifyTime is not set.

- scr/Plugin.LocalNotification/Platform/iOS/LocalNotificationDelegate.cs
Fix issue #11 
Clear badge after click local notification
> [iOS]Remove icon badges after tap on notification

- Sample/Direct/LocalNotification.Sample.iOS/AppDelegate.cs
- Sample/NuGet/Sample.iOS/AppDelegate.cs
Remove badges in iOS10+ if user clear notification in notification panel
Remove badges in iOS10+ if user clear notification in notification panel
> Remove badges in iOS10+ if user clear notification in notification panel

- scr/Plugin.LocalNotification/AndroidOptions.cs
- scr/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
It adds support for icon/app name colors on Android. https://i.imgur.com/MteCi2e.png
Most applications behave this way on android. It also allows you to further distinct your application from others.
> Added support for Android notification color

- scr/Plugin.LocalNotification/AndroidOptions.cs
- scr/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
Added channel name and desciption to android options for android notifications
User can configure notification category for app: enabled, sound (from device), vibrate, etc.
> Android channel name and description

- Source/Plugin.LocalNotification/Plugin.LocalNotification.csproj
- Upgrade the package Xamarin.AndroidX.Work.Runtime from 2.2.0 to 2.3.3.
- Add the missing package Xamarin.AndroidX.Core version 1.2.0.
The upgrade of Xamarin.AndroidX.Work.Runtime from 2.2.0 to 2.3.3 removed AndroidX.Core.App.NotificationCompat. AndroidX.Core.App.NotificationCompat is now located in the package Xamarin.AndroidX.Core version 1.2.0.
> Dependabot/nuget/source/xamarin.android x.work.runtime 2.3.3

- Source/Plugin.LocalNotification/Platform/iOS/NotificationServiceImpl.cs
When an iOS notification is scheduled for a different month / year on the same day, the notification would trigger.
I need to be able to schedule notifications in iOS for the next three months.
> Schedule iOS notifications correctly for future months / years

- README.md
- Sample/Direct/LocalNotification.Sample.Android/LocalNotification.Sample.Android.csproj
- Sample/Direct/LocalNotification.Sample/MainPage.xaml
- Sample/Direct/LocalNotification.Sample/MainPage.xaml.cs
- Source/Plugin.LocalNotification/INotificationService.cs
- Source/Plugin.LocalNotification/NotificationReceivedEventArgs.cs
- Source/Plugin.LocalNotification/NotificationRequest.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/Platform/Droid/ScheduledNotificationWorker.cs
- Source/Plugin.LocalNotification/Platform/iOS/LocalNotificationDelegate.cs
- Source/Plugin.LocalNotification/Platform/iOS/NotificationCenter.cs
- Source/Plugin.LocalNotification/Platform/iOS/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/iOSOptions.cs
Fixes #105 
While using this plugin i missed the functionality (expecially on Android) to being able to display a custom banner when a notification is received and the app is in foreground.
Push notifications plugins are exposing the `NotificationReceived` event, so why not add it to local notifications? :smile:
This PR adds the new event `NotificationReceived` with the following args:
```csharp
/// <summary>
/// Returning event when a notification is received.
/// On iOS this event is fired only when the app is in foreground
/// </summary>
public class NotificationReceivedEventArgs : EventArgs
{
/// <summary>
/// Returning title when a notification is received.
/// </summary>
public string Title { get; internal set; }
/// <summary>
/// Returning details when a notification is received. …
```
> Notification received event

- Source/Plugin.LocalNotification/NotificationRequest.cs
- Source/Plugin.LocalNotification/Platform/Droid/ScheduledNotificationWorker.cs
- Source/Plugin.LocalNotification/Platform/iOS/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/TimeSpanExt.cs
Fixes #117
- Additional backward compatibility with `TimeSpan`
> Add TimeSpan deserialization wrapper

- Source/Plugin.LocalNotification/Platform/Droid/BootReceiver.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/Platform/Droid/ScheduledNotificationWorker.cs
Fixes #122
Also related to #98
- Some changes current one-time worker to executes repetitions;
- Add boot receiver to resume WorkerManager after device restart;
Still actual, known issues:
- Android Doze and App Standby limitate one-time worker execution - notifications can't display, only when charging and etc. (Xiaomi) [[Power management restrictions](https://developer.android.com/topic/performance/power/power-details)]
Proposals for future:
- Rework to [PeriodicWorkRequestBuilder](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work)
- Rework to [AlarmManager](https://developer.android.com/training/scheduling/alarms)
> Rework repeat worker to circular execution

- Sample/Direct/LocalNotification.Sample/MainPage.xaml
- Sample/Direct/LocalNotification.Sample/MainPage.xaml.cs
- Source/Plugin.LocalNotification/Platform/iOS/LocalNotificationDelegate.cs
- Source/Plugin.LocalNotification/Platform/iOS/NotificationCenter.cs
- Source/Plugin.LocalNotification/Platform/iOS/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/iOSOptions.cs
It provides the option for NotificationRequest to have iOS receive a local notification and play sound when in foreground (as issued here https://github.com/thudugala/Plugin.LocalNotification/issues/139). It also provides a new sample option to turn it on/off. Seems to be working with custom sounds as well.
This is a standard behavior on iOS and will come in handy for many occasions https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html -> Handling Notifications When Your App Is in the Foreground
> Add foreground sound option ios

- Source/Plugin.LocalNotification/AndroidOptionsBuilder.cs
- Source/Plugin.LocalNotification/NotificationRequest.cs
- Source/Plugin.LocalNotification/NotificationRequestBuilder.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationCenter.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationChannelGroupRequest.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationChannelGroupRequestBuilder.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationChannelRequest.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationChannelRequestBuilder.cs
- Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/Platform/iOS/NotificationServiceImpl.cs
- Source/Plugin.LocalNotification/Plugin.LocalNotification.csproj
- Source/Plugin.LocalNotification/iOSOptionsBuilder.cs
closes #141
Implement basic fluent pattern for creating a NotificationChannel and a NotificationRequest.
Also adds a boolean value for BypassDND option.
EDIT:
Added Fluent builder for AndroidOptions & iOSOptions,
Added a better way to create the builder on Show(...)
in current context, builder can be called like so:
```cs
Show((builder) => builder
.NotifyAt(DateTime.Now.AddSeconds(10))
.WithDescription("SampleDescription")
.WithNotificationId(10)
.WithTitle("SampleTitle")
.WithAndroidOptions((android) => android
.WithAutoCancel(true)
.WithChannelId("General")
.WithOngoingStatus(true)
.WithPriority(NotificationPriority.High)
.Build())
.WithiOSOptions((ios) => ios
.WithForegroundAlertStatus(false)
.WithForegroundSoundStatus(true)
.Build())
.Create());
```
And to create a …
> Fluent Request Builders for NotificationChannelRequest & NotificationRequest

- README.md
- Source/Plugin.LocalNotification/NotificationRequest.cs
Updates the readme sample with the request builder type.
I just thought it might be good idea to add it in readme as it is implemented in source.
> Update readme samples with new Request Builder models & Implement Show() and Cancel() on NotificationRequest #148

- Source/Plugin.LocalNotification/Plugin.LocalNotification.csproj
Fix a nuget dependency incompatibility with the latest Xamarin.Forms service release.
Plugin.LocalNotification currently depends on Xamarin.AndroidX.Core version >= 1.6.0 since the 8.0.2 release. In the latest Xamarin.Forms nuget release (v. 5.0.0.2083), the Xamarin team added an additional restriction to the Xamarin.AndroidX.Core nuget version which require a version in the following range: >= 1.3.2.3 && < 1.4.0.
This PR reduce the Xamarin.AndroidX.Core nuget dependency version to 1.3.2.3 to ensure compatibility with projects building on the latest Xamarin.Forms release.
I suggest to upgrade back the version of Xamarin.AndroidX.Core to 1.6.0 once the Xamarin team lift the restriction on a future Xamarin.Forms release.
> Reduced Xamarin.AndroidX.Core nuget dependency version to 1.3.2.3

- Source/Plugin.LocalNotification/Platform/Droid/BootReceiver.cs
Adds a check in BootReceiver to see if the request NotifyTime has already passed before calling GetNextNotifyTime() to increment the repeating notification by the specified time.
Multiple reboots on an Android device before the NotifyTime is reached will push the NotifyTime further and further into the future.
As described in #251
> Fixes thudugala/Plugin.LocalNotification#251 Add NotifyTime check to BootReceiver

- Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
Fixes the FLAG_IMMUTABLE error thrown by Android Version 31 and above, specifically when calling the Cancel method of NotificationServiceImpl.cs
My application started crashing on its call to Notification Factory's DeleteGroup method. This fixes that error.
> FLAG_IMMUTABLE Bugfix for Android Version 31 and above.

- Source/Plugin.LocalNotification/Plugin.LocalNotification.csproj
iOS build was failing because StartsWith framework `-ios` will forever be impossible, also tidied up the csproj a little
#270
> Fix building for iOS with maui

- Source/Plugin.LocalNotification/Platforms/iOS/NotificationServiceImpl.cs
Android was referenced to check for at least version 10 of the Operating System on the Notification Service implementation for IOS. This reference was updated to match the rest of the IOS Implementation in the file.
> Removed Android Version check in IOS Implementation

- Source/Plugin.LocalNotification/NotificationRequest.cs
Correct a typo in a property's documentation.
Started using the library, noticed the typo, and would like to fix it for you.
> Correct documentation typo

- Source/Plugin.LocalNotification/Platforms/Android/LocalNotificationCenter.cs
- Source/Plugin.LocalNotification/Platforms/Android/PlatformExtensions.cs
If developer doesnt store sound as Android resource correctly in `raw` folder an exception is triggered
I missed a part in docs where was explained where should be the sound stored. This way it becomes more obvious.
> Added debug error exception

- Source/Plugin.LocalNotification/Plugin.LocalNotification.csproj
Just updating package: `Xamarin.GooglePlayServices.Location` to the latest version
Google play keeps reporting problem:
`Your use of exact alarms is causing your app to crash for some Android users`
and also:
`Library versions that have known defects. Your app has dependencies on these versions. If not updated, these defective library versions may cause your app to crash.`
the library with defect is `com.google.android.gms` and this package contains updated version.
Could potentially solve: https://github.com/thudugala/Plugin.LocalNotification/issues/465
> Updated GooglePlayServices nuget
